In [6]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf

import sys

'''
Reusing code:
https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/

Explaining result:
https://datascience.stackexchange.com/questions/65839/macro-average-and-weighted-average-meaning-in-classification-report


Test_fearMat_Clean: 4168
    Before edit: 4231 rows × 34 columns
    After edit: 4168 rows × 34 columns
    
    #removed 6 to 7
    total = 3749         (20% = 750; 80% = 2,999)
    

Train_fearMat_Clean: 16680
    Before edit: 16927 rows × 34 columns
    After edit: 16680 rows × 34 columns
    
    #removed 6 to 7
    total = 15045         (20% = 3,009; 80% = 12,036)

'''

import os
#print(os.listdir(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900"))         #print out what's in the file/directory

#train = pd.read_csv(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900\featMatVersion2_10.csv")         #using test


print(os.listdir(r"."))         #print out what's in the file/directory
train = pd.read_csv(r"featMatVersion2_10.csv")


#train = pd.read_csv(r"Test_dataset.csv")         #using test
#test = pd.read_csv(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900\Train_dataset.csv")

['CISC 4900 First Interim Report - Eddie Lam.pdf', 'CombinedRows.csv', 'EditingDataset_V3.java', 'featMat.csv', 'featMatVersion2_10.csv', 'featMatVersion2_5.csv', 'featMatVersion2_6.csv', 'featMatVersion2_7.csv', 'featMatVersion2_8.csv', 'featMatVersion2_9.csv', 'features', 'Old dataset', 'Test_dataset.csv', 'Touchalytics-ProjectDef.pdf', 'Train_dataset.csv']


In [ ]:
#print
train.head()

In [7]:
np.any(np.isnan(train))

False

In [8]:
np.all(np.isfinite(train))

True

In [ ]:
#print out the columns
train.columns

In [ ]:
#prints the amount of users in 'User_ID'
train['User_ID'].value_counts()

In [9]:
#Choosing the columns for X
#Not using 'User_ID', 'Doc_ID', or 'Phone_ID'
X = train[['Inter-Stroke time', 'Stroke Duration', 'Start X', 'Start Y', 'Stop X', 'Stop Y', 'Direct end-to-end Distance',
        'Mean resulant length', 'WSAD Flag', 'Direction of end-to-end Time', '20 per pairwise velocity', 
        '50 per pairwise velocity', '80 per pairwise velocity', '20 per pairwise acc', '50 per pairwise acc', 
        '80 per pairwise acc', 'Median velocity at last 3pts', 'Largest deviation from end-to-end line', '20 per dev line',
        '50 per dev line', '80 per dev line', 'Average Direction', 'Length of Trajectory', 
        'Ratio dist and length of trajectory', 'Average velocity', 'Median acceleration at first 5 pts',
        'Mid-Stroke pressure', 'Mid-Stroke area covered', 'Mid-Stroke finger orientation', 'Change of finger orientation',
        'Phone orientation']].values

In [10]:
#Choosing the lables for y
y = train['User_ID'].values

In [11]:
#Train and test split
#80% train, 20% test
#splitting the data into test and train dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [12]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
#Training and Prediction
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)         #value for k
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [14]:
#Make prediction on the test data
y_pred = classifier.predict(X_test)

In [15]:
#Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 66   0   0 ...   0   0   0]
 [  0 204   0 ...   1   0   0]
 [  3   1  64 ...   0   0   0]
 ...
 [  0   5   1 ...  29   0   0]
 [  0   0   4 ...   0  31   0]
 [  1   1   0 ...   1   0  33]]
              precision    recall  f1-score   support

           1       0.69      0.73      0.71        90
           2       0.73      0.87      0.79       235
           3       0.43      0.39      0.41       166
           4       0.63      0.69      0.65        54
           5       0.46      0.58      0.51        90
           6       0.54      0.68      0.60       103
           7       0.57      0.57      0.57       121
           8       0.54      0.66      0.60       113
           9       0.60      0.80      0.69        76
          10       0.58      0.47      0.52        80
          11       0.51      0.72      0.60        75
          12       0.73      0.74      0.74        66
          13       0.56      0.35      0.44        62
          14       0.65      0.86      0.74       1

In [16]:
#prints the entire confusion matrix
#however, it doesnn't fit the entire row and loops around
np.set_printoptions(threshold=sys.maxsize)
resultCM = (confusion_matrix(y_test, y_pred))
print(resultCM)

[[ 66   0   0   2   0   0   5   0   0   0   0   0   0   0   1   0   0   0
    0   2   0   3   2   0   1   0   0   4   0   2   0   0   0   1   0   1
    0   0   0   0   0]
 [  0 204   0   0   1   0   1   0   1   0   0   0   0   0   3   0   0   0
    0   1   0   2   4   4   2   0   1   4   1   0   0   0   0   0   0   2
    0   3   1   0   0]
 [  3   1  64   0   2   7   0   4   0   4   6   2   0   0   0   7  20   9
    4   0   7   0   0   0   0   0   7   0   0   0   0   1   0   0  14   0
    4   0   0   0   0]
 [  0   2   0  37   3   0   0   0   0   0   0   0   0   1   0   0   0   0
    0   1   0   0   1   0   0   0   0   1   0   0   0   0   1   4   0   0
    0   1   1   0   1]
 [  0   1   7   0  52   0   0   3  10   1   0   2   0   1   0   0   1   0
    3   0   0   0   0   2   0   0   3   0   0   0   0   1   0   0   1   0
    2   0   0   0   0]
 [  0   1   1   0   2  70   0   4   0   0   3   0   2   0   0   6   2   0
    1   0   2   0   0   0   0   0   2   1   0   0   1   0   0   0   3  

In [17]:
resultCR = (classification_report(y_test, y_pred))
print(resultCR)

              precision    recall  f1-score   support

           1       0.69      0.73      0.71        90
           2       0.73      0.87      0.79       235
           3       0.43      0.39      0.41       166
           4       0.63      0.69      0.65        54
           5       0.46      0.58      0.51        90
           6       0.54      0.68      0.60       103
           7       0.57      0.57      0.57       121
           8       0.54      0.66      0.60       113
           9       0.60      0.80      0.69        76
          10       0.58      0.47      0.52        80
          11       0.51      0.72      0.60        75
          12       0.73      0.74      0.74        66
          13       0.56      0.35      0.44        62
          14       0.65      0.86      0.74       130
          15       0.68      0.74      0.71       142
          16       0.44      0.44      0.44        93
          17       0.56      0.65      0.60       144
          18       0.70    

In [ ]:
'''
'macro':
 Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.

'weighted':
 Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label).
 This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.
'''