In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf

'''
https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/

Test_fearMat_Clean: 4168
    Before edit: 4231 rows × 34 columns
    After edit: 4168 rows × 34 columns
    
    #removed 6 to 7
    total = 3749
    

Train_fearMat_Clean: 16680
    Before edit: 16927 rows × 34 columns
    After edit: 16680 rows × 34 columns
    
    #removed 6 to 7
    total = 15045

'''

import os
print(os.listdir(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900"))         #print out what's in the file/directory

train = pd.read_csv(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900\Test_datset.csv")         #using test


test = pd.read_csv(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900\Train_dataset.csv")         #will use later code works

['featMatVersion2_5.csv', 'features', 'Old dataset', 'Test_dataset-DESKTOP-7C3T3SE.csv', 'Test_dataset.csv', 'Test_featMat.csv', 'Test_featMat_Clean.csv', 'Touchalytics-ProjectDef.pdf', 'Train_dataset.csv', 'Train_featMat.csv', 'Train_featMat_Clean.csv']


In [ ]:
#print
train.head()

In [ ]:
#prints the selected columns
train_knn = train[['User_ID', 'Doc_ID', 'Phone_ID', 'Ratio dist and length of trajectory', 'Average velocity', 'Phone orientation']]
train_knn.head()

In [ ]:
#The X variable contains the first five columns of the dataset (i.e. attributes) while y contains the labels.
#5 columns and 1 label
X = train_knn.iloc[:, :-1].values         #contain all columns except the last one
y = train_knn.iloc[:, 5].values         #contains the labels, 5 for test, but 33 for the whole test

In [ ]:
#Train and test split
#80% train, 20% test
#splitting the data into test and train dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
#Training and Prediction
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)         #value for k
classifier.fit(X_train, y_train)

In [ ]:
#Make prediction on the test data
y_pred = classifier.predict(X_test)

In [ ]:
#Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


#will print out the accuracy of the test set
#accuracy
    #macro avg: 87.75
    #weighted avg: 97.25

In [ ]:
#Comparing error rate with the K value
error = []

# Calculating error for K values between 1 and 100
for i in range(1, 100):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    error.append(np.mean(pred_i != y_test))

In [ ]:
#plotting the result in a graph
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 10))
plt.plot(range(1, 100), error, color='red', linestyle='dashed', marker='o',
         markerfacecolor='blue', markersize=10)
plt.title('Error Rate K Value')
plt.xlabel('K Value')
plt.ylabel('Mean Error')

In [ ]:
'''
#test 1:
[[783  10]
 [ 11  30]]
              precision    recall  f1-score   support

           1       0.99      0.99      0.99       793
           2       0.75      0.73      0.74        41

    accuracy                           0.97       834
   macro avg       0.87      0.86      0.86       834
weighted avg       0.97      0.97      0.97       834

#test 2:
[[776  14]
 [ 14  30]]
              precision    recall  f1-score   support

           1       0.98      0.98      0.98       790
           2       0.68      0.68      0.68        44

    accuracy                           0.97       834
   macro avg       0.83      0.83      0.83       834
weighted avg       0.97      0.97      0.97       834

#test 3:
[[771   6]
 [ 13  44]]
              precision    recall  f1-score   support

           1       0.98      0.99      0.99       777
           2       0.88      0.77      0.82        57

    accuracy                           0.98       834
   macro avg       0.93      0.88      0.91       834
weighted avg       0.98      0.98      0.98       834

#test 4:
[[774  10]
 [ 14  36]]
              precision    recall  f1-score   support

           1       0.98      0.99      0.98       784
           2       0.78      0.72      0.75        50

    accuracy                           0.97       834
   macro avg       0.88      0.85      0.87       834
weighted avg       0.97      0.97      0.97       834
'''

In [ ]:
#describe the column
train.describe()

#print out the lables/column and there datatype
train.dtypes

#prints out the columns
train.columns

In [ ]:
#prints how many there are in 'Doc_ID'
train['Doc_ID'].value_counts()

In [ ]:
#np.isnan(train_knn)
#np.where(np.isnan(X))
#np.nan_to_num(train_knn)

#pd.DataFrame(train_knn).fillna(0)
#train_knn.fillna(train_knn.mean(), inplace=True)

In [ ]:
'''
Testing with the entire columns on train
'''

In [ ]:
#The X variable contains the first 33 columns of the dataset (i.e. attributes) while y contains the labels.
#33 columns and 1 label
X = train.iloc[:, :-1].values         #contain all columns except the last one
y = train.iloc[:, 33].values         #contains the labels, 3 for the whole test

In [ ]:
#Train and test split
#80% train, 20% test
#splitting the data into test and train dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
#Training and Prediction
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)         #value for k
classifier.fit(X_train, y_train)

In [ ]:
#Make prediction on the test data
y_pred = classifier.predict(X_test)

In [ ]:
#Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

In [ ]:
#Comparing error rate with the K value
error = []

# Calculating error for K values between 1 and 100
for i in range(1, 100):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    error.append(np.mean(pred_i != y_test))

In [ ]:
#plotting the result in a graph
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 10))
plt.plot(range(1, 100), error, color='red', linestyle='dashed', marker='o',
         markerfacecolor='blue', markersize=10)
plt.title('Error Rate K Value')
plt.xlabel('K Value')
plt.ylabel('Mean Error')