In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf

import sys
import os
#this is how I import files
#print(os.listdir(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900"))         #print out what's in the file/directory
#train = pd.read_csv(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900\featMatVersion2_10.csv")         #using test


print(os.listdir(r"."))         #print out what's in the file/directory
train = pd.read_csv(r"featMatVersion2_10.csv")

['CISC 4900 First Interim Report - Eddie Lam.pdf', 'DataSet_V4.csv', 'EditingDataset_V3.java', 'featMat.csv', 'featMatVersion2_10.csv', 'featMatVersion2_8.csv', 'featMatVersion2_9.csv', 'features', 'Old Code', 'Old dataset', 'Project Code 2 Part 1.ipynb', 'Project Code 2 Part 2.ipynb', 'Touchalytics-ProjectDef.pdf', 'ZeroTable.csv']


In [ ]:
#print
train.head()

In [ ]:
#check to see if there is any 'NaN' in your dataset
np.any(np.isnan(train))

In [ ]:
#check to see if there is any 'Inf' in your dataset
np.all(np.isfinite(train))

In [ ]:
#print out the columns
train.columns

In [ ]:
#prints the amount of users in 'User_ID'
train['User_ID'].value_counts()

In [2]:
#Choosing the columns for X
#Not using 'User_ID', 'Doc_ID', or 'Phone_ID'
X = train[['Inter-Stroke time', 'Stroke Duration', 'Start X', 'Start Y', 'Stop X', 'Stop Y', 'Direct end-to-end Distance',
        'Mean resulant length', 'WSAD Flag', 'Direction of end-to-end Time', '20 per pairwise velocity', 
        '50 per pairwise velocity', '80 per pairwise velocity', '20 per pairwise acc', '50 per pairwise acc', 
        '80 per pairwise acc', 'Median velocity at last 3pts', 'Largest deviation from end-to-end line', '20 per dev line',
        '50 per dev line', '80 per dev line', 'Average Direction', 'Length of Trajectory', 
        'Ratio dist and length of trajectory', 'Average velocity', 'Median acceleration at first 5 pts',
        'Mid-Stroke pressure', 'Mid-Stroke area covered', 'Mid-Stroke finger orientation', 'Change of finger orientation',
        'Phone orientation']].values

In [3]:
#Choosing the lables for y
y = train['User_ID'].values

In [4]:
#Train and test split
#80% train, 20% test
#splitting the data into test and train dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [5]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
#Training and Prediction
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)         #value for k
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [7]:
#Make prediction on the test data
y_pred = classifier.predict(X_test)

In [8]:
#Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 49   0   0 ...   0   0   0]
 [  1 210   0 ...   5   1   0]
 [  0   2  74 ...   0   0   0]
 ...
 [  0   2   0 ...  40   0   0]
 [  0   2   0 ...   0  30   0]
 [  1   1   0 ...   0   0  29]]
              precision    recall  f1-score   support

           1       0.62      0.68      0.65        72
           2       0.71      0.87      0.78       241
           3       0.52      0.48      0.50       154
           4       0.65      0.68      0.66        62
           5       0.42      0.54      0.47        81
           6       0.55      0.66      0.60       112
           7       0.58      0.49      0.53       126
           8       0.45      0.65      0.53       109
           9       0.67      0.79      0.73        77
          10       0.81      0.65      0.72        85
          11       0.62      0.75      0.68        84
          12       0.70      0.78      0.74        76
          13       0.49      0.47      0.48        60
          14       0.63      0.84      0.72       1

In [9]:
#prints the entire confusion matrix
#however, it doesnn't fit the entire row and loops around
np.set_printoptions(threshold=sys.maxsize)
resultCM = (confusion_matrix(y_test, y_pred))
print(resultCM)

[[ 49   0   0   2   0   0   7   1   0   0   0   0   0   0   0   0   0   0
    0   1   0   0   1   0   2   1   0   5   0   0   0   0   0   2   0   0
    0   1   0   0   0]
 [  1 210   0   0   0   2   0   1   2   0   0   0   2   0   3   0   0   0
    0   1   0   0   6   0   0   1   0   3   1   0   0   0   0   0   1   0
    0   1   5   1   0]
 [  0   2  74   1   6   7   0   3   2   3   2   3   1   1   0   3  20   1
    4   0   3   0   0   1   0   0   3   0   0   0   0   3   0   0  11   0
    0   0   0   0   0]
 [  2   0   0  42   2   0   1   1   0   0   0   0   0   1   0   0   0   0
    0   0   0   0   0   2   0   0   0   2   0   4   0   0   0   3   0   0
    0   1   0   0   1]
 [  0   2   7   0  44   1   0   6   6   0   0   1   0   1   0   1   0   0
    4   0   0   0   2   0   0   0   1   0   0   0   1   2   0   0   0   0
    2   0   0   0   0]
 [  0   2   4   0   1  74   0   6   0   0   2   0   5   0   0   2   4   1
    2   0   1   0   0   0   0   0   2   0   0   0   0   0   0   0   4  

In [10]:
resultCR = (classification_report(y_test, y_pred))
print(resultCR)

              precision    recall  f1-score   support

           1       0.62      0.68      0.65        72
           2       0.71      0.87      0.78       241
           3       0.52      0.48      0.50       154
           4       0.65      0.68      0.66        62
           5       0.42      0.54      0.47        81
           6       0.55      0.66      0.60       112
           7       0.58      0.49      0.53       126
           8       0.45      0.65      0.53       109
           9       0.67      0.79      0.73        77
          10       0.81      0.65      0.72        85
          11       0.62      0.75      0.68        84
          12       0.70      0.78      0.74        76
          13       0.49      0.47      0.48        60
          14       0.63      0.84      0.72       132
          15       0.72      0.66      0.69       161
          16       0.49      0.48      0.48        77
          17       0.58      0.70      0.63       138
          18       0.79    